"""Service interface for interacting with Ollama to generate code and repository explanations."""

import ollama

MODEL_NAME = "llama3:8b"
NUM_CTX = 8192


def ask_llm(prompt: str, system: str = "") -> str:
    """Send a prompt to the local Ollama LLM and return the generated response text.

    Args:
        prompt: The user prompt to send to the model.
        system: Optional system prompt to instruct the model.

    Returns:
        The response text generated by the model.

    Raises:
        RuntimeError: If the Ollama server is not running or the model is missing.
    """
    options = {"num_ctx": NUM_CTX}

    try:
        response = ollama.generate(
            model=MODEL_NAME,
            prompt=prompt,
            system=system if system else None,
            options=options,
        )
        return response.response or ""
    except ConnectionError:
        raise RuntimeError(
            "Ollama server is not running or unreachable. "
            "Please ensure Ollama is installed and running (e.g., run 'ollama serve')."
        ) from None
    except ollama.ResponseError as exc:
        if exc.status_code == 404 or "not found" in str(exc).lower():
            raise RuntimeError(
                f"Model '{MODEL_NAME}' was not found in Ollama. "
                f"Please download it first by running: ollama pull {MODEL_NAME}"
            ) from None
        raise RuntimeError(f"Ollama response error (status {exc.status_code}): {exc.error}") from None
    except ollama.RequestError as exc:
        raise RuntimeError(f"Ollama request error: {exc.error}") from None


import fnmatch
import re

MAX_FILE_CHARS = 3000
HEAD_CHARS = 1500
OUTLINE_CHARS = 2000
README_CHARS = 6000
MAX_FILES = 15
DEBUG_RAW_OUTPUT = True

# Files that provide little architectural value for repository summarization
LOW_VALUE_PATTERNS = [
    "*.css",
    "*.min.js",
    "*.test.*",
    "*.spec.*",
    "robots.txt",
    "manifest.json",
    "package-lock.json",
    "setupTests.*",
    "reportWebVitals.*",
]

# Entry point patterns/filenames
_ENTRY_POINTS = {
    "main.py",
    "app.py",
    "index.js",
    "index.ts",
    "index.jsx",
    "index.tsx",
    "server.py",
    "server.js",
    "manage.py",
    "cli.py",
    "run.py",
    "main.go",
    "main.rs",
    "index.html",
}

# Key manifests and dependency configuration files
_MANIFESTS = {
    "requirements.txt",
    "package.json",
    "pyproject.toml",
    "setup.py",
    "cargo.toml",
    "go.mod",
    "pom.xml",
    "dockerfile",
}

# Standard source code file extensions
_SOURCE_EXTENSIONS = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".java",
}

# High-value architectural keywords to prioritize
_BONUS_KEYWORDS = {
    "app",
    "main",
    "server",
    "routes",
    "models",
    "config",
    "api",
    "service",
}


def build_outline(path: str, content: str) -> str:
    """Find definitions using generic regexes and return a compact outline.

    Extracts:
    - Python: class and def names, and decorators like @app.route(...)
    - JS/TS/JSX: function names, class names, const/let arrow-function names,
      React components, and route calls like app.get / router.post / app.route
    - Other file types: returns an empty string

    Deduplicates while preserving original order, and truncates at OUTLINE_CHARS.
    """
    norm_path = path.replace("\\", "/").lower()
    suffix = "." + norm_path.rsplit(".", 1)[1] if "." in norm_path else ""
    raw_items: list[str] = []

    if suffix in {".py", ".ipynb"}:
        for line in content.splitlines():
            # Decorators (e.g., @app.route(...), @login_required)
            m_dec = re.match(r"^\s*(@[A-Za-z0-9_.]+(?:\([^)]*\))?)", line)
            if m_dec:
                raw_items.append(m_dec.group(1).strip())

            # Classes
            m_cls = re.match(r"^\s*class\s+([A-Za-z0-9_]+(?:\([^)]*\))?)", line)
            if m_cls:
                raw_items.append(f"class {m_cls.group(1).strip()}")
                continue

            # Functions / Methods
            m_def = re.match(r"^\s*(?:async\s+)?def\s+([A-Za-z0-9_]+)", line)
            if m_def:
                raw_items.append(f"def {m_def.group(1).strip()}")
                continue

    elif suffix in {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}:
        for line in content.splitlines():
            # Route calls (e.g., app.get, router.post, app.route)
            m_route = re.search(
                r"\b((?:app|router)\.(?:get|post|put|delete|patch|use|all|route)\s*\([^)]*?\))",
                line,
            )
            if m_route:
                raw_items.append(m_route.group(1).strip())

            # Classes
            m_cls = re.match(
                r"^\s*(?:export\s+(?:default\s+)?)?class\s+([A-Za-z0-9_$]+(?:\s+extends\s+[A-Za-z0-9_$.]+)?)",
                line,
            )
            if m_cls:
                raw_items.append(f"class {m_cls.group(1).strip()}")
                continue

            # Functions
            m_fn = re.match(
                r"^\s*(?:export\s+(?:default\s+)?)?(?:async\s+)?function(?:\s+([A-Za-z0-9_$]+))?",
                line,
            )
            if m_fn and m_fn.group(1):
                name = m_fn.group(1).strip()
                suffix_tag = " (React component)" if name[0].isupper() else ""
                raw_items.append(f"function {name}{suffix_tag}")
                continue

            # Arrow functions (const/let/var name = ... =>)
            m_arrow = re.match(
                r"^\s*(?:export\s+)?(?:const|let|var)\s+([A-Za-z0-9_$]+)\s*=\s*(?:async\s*)?(?:\([^)]*\)|[A-Za-z0-9_$]+)?\s*=>",
                line,
            )
            if m_arrow:
                name = m_arrow.group(1).strip()
                suffix_tag = " (React component)" if name[0].isupper() else ""
                raw_items.append(f"const {name} = (...) =>{suffix_tag}")
                continue

            # Function expressions (const/let/var name = function)
            m_expr = re.match(
                r"^\s*(?:export\s+)?(?:const|let|var)\s+([A-Za-z0-9_$]+)\s*=\s*(?:async\s*)?function",
                line,
            )
            if m_expr:
                name = m_expr.group(1).strip()
                suffix_tag = " (React component)" if name[0].isupper() else ""
                raw_items.append(f"const {name} = function{suffix_tag}")
                continue

    else:
        return ""

    # Remove duplicates while preserving original order
    seen = set()
    unique_items: list[str] = []
    for item in raw_items:
        clean = item.strip()
        if clean and clean not in seen:
            seen.add(clean)
            unique_items.append(clean)

    # Truncate at OUTLINE_CHARS
    outline_lines: list[str] = []
    curr_len = 0
    for item in unique_items:
        item_len = len(item) + 1
        if curr_len + item_len > OUTLINE_CHARS:
            outline_lines.append("... [outline truncated]")
            break
        outline_lines.append(item)
        curr_len += item_len

    return "\n".join(outline_lines)


def compress_code(path: str, content: str) -> str:
    """Compress large source files by combining the file header with definition outlines.

    If len(content) <= MAX_FILE_CHARS, return content unchanged.
    Otherwise return first HEAD_CHARS chars, a notification line, and build_outline output.
    """
    if len(content) <= MAX_FILE_CHARS:
        return content

    head = content[:HEAD_CHARS]
    outline = build_outline(path, content)

    outline_lines = [
        line.strip()
        for line in outline.splitlines()
        if line.strip() and not line.startswith("... [")
    ]
    def_count = len(outline_lines)

    compressed = (
        f"{head}\n"
        "[... file is large, showing outline of definitions ...]\n"
        f"{outline}"
    )

    print(
        f"Compressed {path}: {len(content)} -> {len(compressed)} chars, {def_count} definitions found"
    )
    return compressed


def summarize_file(path: str, content: str) -> str:
    """Generate a 2-3 line plain-English summary of what a single file does.

    Args:
        path: Relative path of the file.
        content: Source code text of the file.

    Returns:
        A concise 2-3 line summary.
    """
    is_compressed = len(content) > MAX_FILE_CHARS
    prepared_code = compress_code(path, content)

    system_prompt = (
        "You are an expert software engineer analyzing source files. "
        "Provide clear, accurate, plain-English summaries based strictly on the provided code."
    )

    if is_compressed:
        compression_note = (
            "\nNOTE: This file is large. You only see the start of the file plus a list of its definitions "
            "(classes, functions, routes). Describe the overall purpose of the file based on these visible "
            "components and definitions. Do NOT assume or claim details you cannot see.\n"
        )
    else:
        compression_note = ""

    user_prompt = (
        f"File: {path}\n\n"
        f"Code:\n```\n{prepared_code}\n```\n{compression_note}\n"
        "Explain what this file does in 2 to 3 lines of plain English.\n"
        "Use ONLY the given code above. Do not guess, assume, or invent any details not present in the code."
    )

    return ask_llm(user_prompt, system=system_prompt).strip()


def _is_root_readme(path: str) -> bool:
    """Check if the path points to a root-level README file."""
    norm = path.replace("\\", "/").strip()
    if "/" not in norm:
        filename = norm.lower()
        stem = filename.rsplit(".", 1)[0] if "." in filename else filename
        if stem == "readme":
            return True
    return False


def _is_nested_readme(path: str) -> bool:
    """Check if the path points to a nested README file (not in root)."""
    norm = path.replace("\\", "/").strip()
    if "/" in norm:
        filename = norm.split("/")[-1].lower()
        stem = filename.rsplit(".", 1)[0] if "." in filename else filename
        if stem == "readme":
            return True
    return False


def _is_low_value(path: str) -> tuple[bool, str]:
    """Check if a file matches LOW_VALUE_PATTERNS or is a data-only JSON file."""
    norm = path.replace("\\", "/").lower()
    filename = norm.split("/")[-1]

    for pat in LOW_VALUE_PATTERNS:
        if fnmatch.fnmatch(filename, pat.lower()):
            return True, f"Matches low-value pattern '{pat}'"

    # Data-only JSON files (excluding package.json)
    if filename.endswith(".json") and filename != "package.json":
        return True, "Data-only JSON file"

    return False, ""


def _rank_file(path: str) -> tuple:
    """Compute a sorting tuple for remaining files.

    Criteria:
    - Entry points and manifests first (Tier 1)
    - Source code files (.py, .js, .jsx, .ts, .tsx, .java) next (Tier 2)
    - Other configuration and markup files (Tier 3)
    - Nested READMEs at the lowest priority (Tier 4)
    - Bonus for architectural keywords (app, main, server, routes, models, config, api, service)
    - Prefer shallower paths on ties
    - Alphabetical path tie-breaker
    """
    norm = path.replace("\\", "/").lower()
    filename = norm.split("/")[-1]
    stem = filename.rsplit(".", 1)[0] if "." in filename else filename
    suffix = "." + filename.rsplit(".", 1)[1] if "." in filename else ""
    depth = norm.count("/")

    if stem == "readme":
        tier = 4  # Nested README (lowest priority)
    elif (
        filename in _MANIFESTS
        or filename.startswith("dockerfile")
        or filename in _ENTRY_POINTS
        or stem in {"main", "app", "index", "server", "cli", "run", "manage"}
    ):
        tier = 1
    elif suffix in _SOURCE_EXTENSIONS:
        tier = 2
    else:
        tier = 3

    has_keyword = any(kw in filename for kw in _BONUS_KEYWORDS)
    bonus = 1 if has_keyword else 0

    return (tier, -bonus, depth, norm)


def _get_picked_reason(path: str) -> str:
    """Generate a short human-readable description for why a file was picked."""
    norm = path.replace("\\", "/").lower()
    filename = norm.split("/")[-1]
    stem = filename.rsplit(".", 1)[0] if "." in filename else filename
    suffix = "." + filename.rsplit(".", 1)[1] if "." in filename else ""

    matched_kws = [kw for kw in _BONUS_KEYWORDS if kw in filename]
    kw_info = f", keyword '{matched_kws[0]}'" if matched_kws else ""

    if filename in _MANIFESTS or filename.startswith("dockerfile"):
        return f"Manifest / configuration{kw_info}"
    if filename in _ENTRY_POINTS or stem in {"main", "app", "index", "server", "cli", "run", "manage"}:
        return f"Entry point{kw_info}"
    if suffix in _SOURCE_EXTENSIONS:
        return f"Source code ({suffix}){kw_info}"
    if stem == "readme":
        return f"Nested README{kw_info}"
    return f"Source / config ({suffix or filename}){kw_info}"


REQUIRED_HEADINGS = [
    "Project Overview",
    "What the project does",
    "Main Technologies",
    "How it works",
]


def _count_present_headings(text: str) -> int:
    """Count how many of the four required headings are present in the text."""
    low = text.lower()
    return sum(1 for h in REQUIRED_HEADINGS if h.lower() in low)


def _clean_explanation(text: str) -> str:
    """Post-process LLM explanation output.

    - Removes everything before the first line containing 'Project Overview'.
    - Only removes trailing paragraphs starting with 'Note:' or 'Please note'
      if all four sections are present and the note comes after all four sections.
    - Strips leading and trailing blank lines.
    """
    lines = text.splitlines()
    start_idx = None
    for i, line in enumerate(lines):
        if "project overview" in line.lower():
            start_idx = i
            break

    if start_idx is not None:
        lines = lines[start_idx:]

    cleaned = "\n".join(lines).strip()

    # Check if all four sections are present
    all_four_present = _count_present_headings(cleaned) == len(REQUIRED_HEADINGS)

    # Only remove trailing note paragraphs if all four sections are present
    if all_four_present:
        paragraphs = re.split(r"\n\s*\n", cleaned)
        while paragraphs:
            last_para = paragraphs[-1].strip().lower()
            clean_last = re.sub(r"^[*_#`\s]+", "", last_para)
            if clean_last.startswith("note:") or clean_last.startswith("please note"):
                how_it_works_pos = cleaned.lower().rfind("how it works")
                para_pos = cleaned.rfind(paragraphs[-1])
                # Ensure the trailing paragraph comes after the fourth section
                if para_pos > how_it_works_pos:
                    paragraphs.pop()
                    cleaned = "\n\n".join(paragraphs).strip()
                else:
                    break
            else:
                break

    return cleaned.strip()


def explain_repo(file_records: list[dict], file_tree: str) -> str:
    """Analyze repository files, summarize key files, and generate a structured overview.

    Args:
        file_records: List of dicts formatted as {"path": str, "content": str}.
        file_tree: Text tree representation of repository files.

    Returns:
        Structured beginner-friendly explanation of the repository.
    """
    if not file_records:
        return (
            "Project Overview\nNot clear from the code (no source files found).\n\n"
            "What the project does\n- Not clear from the code.\n\n"
            "Main Technologies\n- Not clear from the code.\n\n"
            "How it works\n- Not clear from the code."
        )

    # 1. Separate Root README, nested READMEs (if root exists), low-value files, and candidates
    has_root_readme = any(_is_root_readme(r.get("path", "")) for r in file_records)
    root_readme_record = None
    skipped_files: list[tuple[str, str]] = []
    candidate_records: list[dict] = []

    for record in file_records:
        path = record.get("path", "")

        if _is_root_readme(path):
            root_readme_record = record
            skipped_files.append((path, "Root README (passed directly to final prompt)"))
            continue

        if has_root_readme and _is_nested_readme(path):
            skipped_files.append(
                (path, "Nested README skipped (root README is present)")
            )
            continue

        is_low, reason = _is_low_value(path)
        if is_low:
            skipped_files.append((path, reason))
            continue

        candidate_records.append(record)

    # 2. Extract and truncate root README (or fallback to any nested README)
    if root_readme_record:
        raw_readme = root_readme_record.get("content", "")
        readme_content = raw_readme[:README_CHARS]
        if len(raw_readme) > README_CHARS:
            readme_content += "\n... [README truncated]"
    else:
        # Fallback if no root README exists
        nested_readme = next(
            (r for r in file_records if "readme" in Path(r.get("path", "")).stem.lower()),
            None,
        )
        if nested_readme:
            raw_readme = nested_readme.get("content", "")
            readme_content = raw_readme[:README_CHARS]
            if len(raw_readme) > README_CHARS:
                readme_content += "\n... [README truncated]"
        else:
            readme_content = "No README file found."

    # 3. Rank candidate files and select top MAX_FILES
    ranked_records = sorted(
        candidate_records,
        key=lambda r: _rank_file(r.get("path", "")),
    )
    picked_records = ranked_records[:MAX_FILES]
    overflow_records = ranked_records[MAX_FILES:]

    for record in overflow_records:
        skipped_files.append(
            (record.get("path", ""), f"Exceeded MAX_FILES limit (picked top {MAX_FILES})")
        )

    # 4. Print picked and skipped files with reasons before summarizing
    print("\nFile Selection:")
    for record in picked_records:
        path = record.get("path", "")
        reason = _get_picked_reason(path)
        print(f"  [PICKED]  {path} ({reason})")
    for path, reason in skipped_files:
        print(f"  [SKIPPED] {path} ({reason})")
    print()

    # 5. Summarize each picked file with progress indicator
    file_summaries: list[str] = []
    total_picked = len(picked_records)
    for idx, record in enumerate(picked_records, 1):
        path = record.get("path", "")
        content = record.get("content", "")
        print(f"Summarizing {idx}/{total_picked}: {path}")
        summary = summarize_file(path, content)
        file_summaries.append(f"- **{path}**: {summary}")

    summaries_text = "\n".join(file_summaries) if file_summaries else "No individual files were summarized."

    # 6. Final synthesis prompt to Ollama
    system_prompt = (
        "You are an encouraging and clear programming tutor who explains software codebases "
        "to beginners using simple, plain English without jargon."
    )

    user_prompt = f"""You are analyzing a software repository. Explain this project in simple language as if explaining to a beginner, strictly following the instructions and format below.

CRITICAL INSTRUCTIONS:
1. Output ONLY these four sections in this exact order, with NO introductory sentence, preamble, greeting, or closing remark:
Project Overview
What the project does
Main Technologies
How it works

2. Formatting for sections:
- Project Overview: 2-3 plain-English sentences summarizing what the project is.
- What the project does: Bullet list of primary features using plain "-" bullets only. No nested bullets. Do not repeat the same point in two bullets.
- Main Technologies: Bullet list using plain "-" bullets only. Identify languages, libraries, and frameworks directly from the README and manifests (requirements.txt, package.json, etc.), as well as the file extensions of picked files (for example, .ipynb indicates Jupyter Notebook, .py indicates Python, .ts indicates TypeScript, .js indicates JavaScript). Do not repeat items.
- How it works: A short, numbered step-by-step flow (1., 2., 3.) describing steps in the order data actually flows, strictly as stated in the README or visible in the file summaries. Do not claim one step depends on another unless the text explicitly states so.

3. List features as written and described in the README and visible in the code. Do NOT treat sample data, mock datasets, or knowledge-base files as actual application features.
4. For any section, feature, or technology that is missing, ambiguous, or cannot be confirmed from the provided code and manifests, write "Not clear from the code" instead of guessing or inventing details.

---
FILE TREE:
{file_tree}

---
README:
{readme_content}

---
FILE SUMMARIES:
{summaries_text}
"""

    raw_response = ask_llm(user_prompt, system=system_prompt)
    if DEBUG_RAW_OUTPUT:
        print("\n--- RAW OUTPUT START ---")
        print(raw_response)
        print("--- RAW OUTPUT END ---")
        print(f"Raw output length: {len(raw_response)} characters\n")

    result = _clean_explanation(raw_response)
    score1 = _count_present_headings(result)

    # If any required section is missing, retry the final step once
    if score1 < len(REQUIRED_HEADINGS):
        print("A retry happened: missing required section(s) in final explanation.")
        raw_retry = ask_llm(user_prompt, system=system_prompt)
        if DEBUG_RAW_OUTPUT:
            print("\n--- RAW OUTPUT START ---")
            print(raw_retry)
            print("--- RAW OUTPUT END ---")
            print(f"Raw output length: {len(raw_retry)} characters\n")

        result_retry = _clean_explanation(raw_retry)
        score2 = _count_present_headings(result_retry)

        if score2 > score1:
            result = result_retry

    return result

